language: node_js
node_js:
  - '15'
before_install:
  - export TZ=Asia/Shanghai
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: public
  on:
    branch: main
